apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: monitoring
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-operated:9090
        access: proxy
        isDefault: true
        editable: true
        jsonData:
          timeInterval: "30s"
          httpMethod: POST
      - name: AlertManager
        type: alertmanager
        url: http://alertmanager-operated:9093
        access: proxy
        jsonData:
          implementation: prometheus
