apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: coredns
  namespace: monitoring
  labels:
    app.kubernetes.io/name: coredns
    app.kubernetes.io/component: monitoring
    release: prometheus-operator
spec:
  jobLabel: k8s-app
  selector:
    matchLabels:
      k8s-app: kube-dns
  namespaceSelector:
    matchNames:
      - kube-system
  endpoints:
    - port: metrics
      scheme: http
      interval: 30s
      metricRelabelings:
        - sourceLabels: [__name__]
          regex: 'coredns_(dns_request_count_total|dns_response_rcode_count_total|cache_hits_total|cache_misses_total)'
          action: keep
