apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-scheduler
  namespace: monitoring
  labels:
    app.kubernetes.io/name: kube-scheduler
    app.kubernetes.io/component: monitoring
    release: prometheus-operator
spec:
  jobLabel: k8s-app
  selector:
    matchLabels:
      k8s-app: kube-scheduler
  namespaceSelector:
    matchNames:
      - kube-system
  endpoints:
    - port: http-metrics
      scheme: http
      interval: 30s
      metricRelabelings:
        - sourceLabels: [__name__]
          regex: 'scheduler_(schedule_attempts_total|scheduling_duration_seconds|binding_duration_seconds)'
          action: keep
