apiVersion: v1
kind: Namespace
metadata:
  name: harbor-system
  labels:
    name: harbor-system
    app.kubernetes.io/name: harbor
    app.kubernetes.io/component: registry
    app.kubernetes.io/part-of: cicd-platform
