apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  labels:
    app: cicd-backend
type: Opaque
stringData:
  password: "CHANGE_ME_DATABASE_PASSWORD"
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  labels:
    app: cicd-backend
type: Opaque
stringData:
  secret: "CHANGE_ME_JWT_SECRET"
